Annoy Index Management 및 Bulk Validate 추가
handong-app/handong-feed-validator pull request #12
Opened 2024-12-29 09:56 UTC by Callein

## 추가된 API
- `/api/kafeed/validate/bulk`
  - req
    ```json
    {
      "requests": [
          {
            "chat_id": 0,
            "client_message_id": 0,
            "room_id": 0,
            "user_id": 0,
            "message": "string",
            "sent_at": 0
          }
      ]
    }
    ```
  - res
  
      ```json
      {
        "responses": [
          {
            "message_id": "string",
            "chat_id": 0,
            "message": "string",
            "subject_id": 0
          }
        ]
      }
      ```

## 변경사항
- process_validate가 single과 bulk로 나뉘어졌습니다.
- bulk 요청 시 세션 공유 문제로 인해 validate 호출 시 내부에서 독립적인 세션을 엽니다.
- script 삭제
  - 기존 script 호출 방식 대신 BuildService에서 빌드 관련 로직을 다룹니다.
- Index Manager 구현
  -  어노이 인덱스의 모든 관리와 최신화는 Index Manager 내에서 이루어집니다.
- io_utils 추가
  - io 속도 개선을 위한 sys.stdout 으로 print를 대체했습니다.

2024-12-29 09:58 UTC, Callein commented
log 를 좀 더 깔끔하게 해야하는 작업이 남아있습니다만, 이 일은 다음으로 미루도록 하겠습니다.

2025-01-01 10:22 UTC, junglesub requested changes
README.md 파일에 관련 내용 추가되어야할 것 같습니다.

- [x] /api/kafeed/validate
- [ ] /api/kafeed/validate/bulk 

### 수정 요청
- similar message detection 이 불확실한 것 같습니다.

기존 endpoint 에도 동일한 오류가 발생하는지는 모르겠지만 `/bulk` 으로 테스트 했을 때 새로운 메세지 추가된 이후 동일한 메세지가 들어올 시 다음 메세지에서도 새로운 메세지라고 등록되고 그 다음에 업데이트가 된 것을 확인하였습니다.

### 스크린샷

![image](https://github.com/user-attachments/assets/5723f95b-a062-4f3a-ae47-a9cc92eff94f)

![image](https://github.com/user-attachments/assets/4ef8a569-9600-47d7-878a-fb17274f195d)

2025-01-01 10:28 UTC, junglesub approved these changes
기존에 있던 단일 endpoint 는 작동을 하는 것 같아 서비스 복구를 위해 우선 머지해서 단일 endpoint 와 14일 어노이 최적화를 먼저 사용하고 이후 bulk 수정해도 좋을 것 같습니다.

2025-01-01 10:32 UTC, Callein commented
그럼 우선 머지하면 될까요?

2025-01-01 11:01 UTC, junglesub commented
네 벌크 기능은 지켜보면 될 것 같습니다.

이상현상 발견은 했는데 테스트 목적으로 한거여서 일단 지켜보기만 하면 될 것 같습니다.

https://www.loom.com/share/afffd7202b954d8a87e63649386ebdc3

2025-01-01 11:02 UTC, merged